version: '3.8'

services:
  eureka-server:
    image: openjdk:18-jdk-alpine
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - ./Eureka/target/EurekaSever.jar:/EurekaSever.jar
    entrypoint: ["java", "-jar", "/EurekaSever.jar"]

  config-server:
    image: openjdk:18-jdk-alpine
    container_name: config-server
    ports:
      - "8181:8181"
    volumes:
      - ./config-server/target/config-server.jar:/config-server.jar
    entrypoint: ["java", "-jar", "/config-server.jar"]
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/your-org/your-config-repo
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main

  api-gateway:
    image: openjdk:18-jdk-alpine
    container_name: api-gateway
    ports:
      - "8765:8765"
    volumes:
      - ./api-gateway/target/api-gateway.jar:/gateway.jar
    entrypoint: ["java", "-jar", "/api-gateway.jar"]

  event-app:
    image: openjdk:18-jdk-alpine
    container_name: event-app
    ports:
      - "8081:8081"
    volumes:
      - ./event/target/event.jar:/event.jar
    entrypoint: ["java", "-jar", "/event.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/eventdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8181

  ticket-app:
    image: openjdk:18-jdk-alpine
    container_name: ticket-app
    ports:
      - "8080:8080"
    volumes:
      - /ticket/target/ticket.jar:/ticket.jar
    entrypoint: ["java", "-jar", "/ticket.jar"]
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/ticket
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8181

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: eventdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mysql-data:
  mongo-data:
